apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskapp
  name: simpleflask1
spec:
  type: NodePort
  ports:
    - port: 5070
      targetPort: 5070
      protocol: TCP
  selector:
    app: flaskapp
