apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitorapp
  name: pythonmonitor
spec:
  type: NodePort
  ports:
    - port: 5070
      targetPort: 5070
      protocol: TCP
  selector:
    app: monitorapp
